// milliseconds
export const FILP_TILE_ANIMATION_DURATION = 500;
export const FLIP_TILE_ANIMATION_DELAY = 200;
export const WORD_REVEAL_ANIMATION_DELAY =
  FILP_TILE_ANIMATION_DURATION + FLIP_TILE_ANIMATION_DELAY * 4;
export const MESSAGE_DURATION = 2000;
export const MESSAGE_FADING_TRANSITION = 250;
